fieldLayouts:
  0842377a-7ab2-46f8-8213-5b705578cfd8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 27e41c75-69ba-4ade-8cc6-f016def6c402
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dc5fc0fa-0abf-4dd2-96d2-3569e06bebb2
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 650b331d-a85e-4ba9-ae14-65e8a48f9ef6 # contact
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
