fieldLayouts:
  447baa6b-c1ff-45ee-8b38-46b979bcfcef:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fa13b9e1-fbcb-4247-b33c-ddd336fe7442
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 29f0238d-f003-4d2b-be2e-b6343e49f7b2 # Map
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00d3f712-8124-4207-97b7-8b0a1fd027fe
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 66987c71-2d6d-4ee0-bf0a-4c86b585edd1
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 734c50f9-1d5b-48fe-828f-2812fec5d283 # map
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
