columnSuffix: null
contentColumnType: string
fieldGroup: af7cffae-1be7-4832-aa19-eb21154b1cd0 # Common
handle: bannerImage
instructions: null
name: 'banner image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: false
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:87c27e83-a3b3-45ae-b4ff-4a70a903087f' # furniture-assets
  defaultUploadLocationSubpath: '/banner/{slug}'
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:87c27e83-a3b3-45ae-b4ff-4a70a903087f' # furniture-assets
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
