columnSuffix: pzdhuyma
contentColumnType: text
fieldGroup: af7cffae-1be7-4832-aa19-eb21154b1cd0 # Common
handle: map
instructions: null
name: Map
searchable: false
settings:
  boundary: '""'
  boundaryRestrictionNELat: null
  boundaryRestrictionNELng: null
  boundaryRestrictionSWLat: null
  boundaryRestrictionSWLng: null
  country: BE
  countryRestriction: null
  height: null
  hideAddress: false
  hideLatLng: null
  hideMap: false
  hideSearch: false
  lat: 51.272154
  lng: 0.514951
  maxZoom: 18.0
  minZoom: 3.0
  showCurrentLocation: true
  showLatLng: true
  showW3WField: false
  showW3WGrid: false
  size: normal
  typeRestriction: null
  zoom: 15
translationKeyFormat: null
translationMethod: none
type: ether\simplemap\fields\MapField
