columnSuffix: nsmxpxtb
contentColumnType: text
fieldGroup: af7cffae-1be7-4832-aa19-eb21154b1cd0 # Common
handle: openingHours
instructions: null
name: 'opening hours'
searchable: false
settings:
  slots:
    __assoc__:
      -
        - open
        -
          __assoc__:
            -
              - name
              - open
            -
              - handle
              - open
      -
        - close
        -
          __assoc__:
            -
              - name
              - close
            -
              - handle
              - close
translationKeyFormat: null
translationMethod: none
type: craft\storehours\Field
