columnSuffix: bocflonr
contentColumnType: integer(10)
fieldGroup: af7cffae-1be7-4832-aa19-eb21154b1cd0 # Common
handle: price
instructions: null
name: price
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: null
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
