defaultPlacement: end
enableVersioning: true
handle: home
name: home
propagationMethod: all
siteSettings:
  babdafee-95ba-4e9b-a204-4806bf7b85c3: # cms-examen
    enabledByDefault: true
    hasUrls: true
    template: home/_entry
    uriFormat: 'home/{slug}'
type: channel
