defaultPlacement: end
enableVersioning: true
handle: map
name: map
propagationMethod: all
siteSettings:
  babdafee-95ba-4e9b-a204-4806bf7b85c3: # cms-examen
    enabledByDefault: true
    hasUrls: true
    template: map/_entry
    uriFormat: 'map/{slug}'
type: channel
